"""Vector serialization and intent definition hydration.

Embedding vectors are stored as packed float32 arrays in PostgreSQL BYTEA
columns, matching the existing convention from `bsgateway/routing/collector.py`.
Hydration takes raw DB rows and produces `IntentDefinition` objects, filtering
out stale embeddings (generated by a now-replaced model) and intents that
end up with zero usable examples.
"""

from __future__ import annotations

import struct
from collections.abc import Iterable
from typing import Any

import structlog

from bsgateway.rules.intent import IntentDefinition

logger = structlog.get_logger(__name__)


def serialize_embedding(vec: list[float]) -> bytes:
    return struct.pack(f"{len(vec)}f", *vec)


def deserialize_embedding(data: bytes) -> list[float]:
    count = len(data) // 4
    return list(struct.unpack(f"{count}f", data))


def hydrate_intent_definitions(
    rows: Iterable[Any],
    *,
    active_model: str | None,
) -> list[IntentDefinition]:
    """Convert DB rows from ``list_intent_examples_for_tenant`` into IntentDefinition objects.

    Rows that have no embedding, OR whose ``embedding_model`` does not match the
    tenant's currently active model, are skipped — they are stale and would
    either crash on dimension mismatch or produce nonsense similarity scores.

    Intents that end up with zero usable example embeddings are excluded from
    the result entirely so they cannot match any request.

    Args:
        rows: Records from ``list_intent_examples_for_tenant``.
        active_model: The tenant's currently configured embedding model. If None
            (tenant has no embedding configured), no intents are returned.
    """
    if not active_model:
        return []

    intents: dict[str, IntentDefinition] = {}
    skipped_stale = 0

    for row in rows:
        name = row["intent_name"]
        if name not in intents:
            intents[name] = IntentDefinition(
                name=name,
                description="",
            )

        embedding_bytes = row["embedding"]
        embedding_model = row["embedding_model"]

        if not embedding_bytes:
            continue
        if embedding_model != active_model:
            skipped_stale += 1
            continue

        intents[name].example_embeddings.append(deserialize_embedding(embedding_bytes))

    if skipped_stale:
        logger.info(
            "stale_embeddings_skipped",
            count=skipped_stale,
            active_model=active_model,
            hint="Run re-embed to refresh stale examples for the current model.",
        )

    return [d for d in intents.values() if d.example_embeddings]
