"""Per-tenant embedding configuration loaded from `tenants.settings` JSONB.

Embedding model selection is a tenant-level concern, not an environment-level
one. Different tenants may use different providers (OpenAI, Ollama, Cohere)
and we want to allow swapping models without redeploying. The chosen model is
recorded on each `intent_examples.embedding_model` row so we can detect stale
embeddings (generated by a now-replaced model) and skip them at classification
time without crashing on dimension mismatch.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EmbeddingSettings:
    """Tenant-level embedding configuration.

    Persisted under ``tenants.settings['embedding']`` as JSON. Empty / missing
    means embedding-based intent classification is disabled for the tenant.
    """

    model: str
    api_base: str | None = None
    timeout: float = 10.0
    max_input_length: int = 8000

    @classmethod
    def from_tenant_settings(cls, settings: dict) -> EmbeddingSettings | None:
        """Extract embedding settings from a tenant's settings dict.

        Returns None if no embedding model is configured (feature disabled).
        Schema::

            {
              "embedding": {
                "model": "text-embedding-3-small",
                "api_base": null,
                "timeout": 10.0,
                "max_input_length": 8000
              }
            }
        """
        embedding = (settings or {}).get("embedding")
        if not isinstance(embedding, dict):
            return None
        model = embedding.get("model")
        if not model or not isinstance(model, str):
            return None
        return cls(
            model=model,
            api_base=embedding.get("api_base") or None,
            timeout=float(embedding.get("timeout", 10.0)),
            max_input_length=int(embedding.get("max_input_length", 8000)),
        )

    def to_dict(self) -> dict:
        return {
            "model": self.model,
            "api_base": self.api_base,
            "timeout": self.timeout,
            "max_input_length": self.max_input_length,
        }
